name: Run CI/CD Tests

on: [push, pull_request] # Runs on every push and PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 21  # ✅ Explicitly install Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify Java Version  # ✅ Debug step to check Java version
        run: java -version

      - name: Build & Run Tests
        run: mvn clean compile test
